
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: admin
#  application:
#    name: account-service
  jpa:
    properties:
      hibernate:
        sqldialect: org.hibernate.dialect.MySQLDialect
        showsql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

 
    