server:
  port: 8081
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: admin
#  application:
#    name: customer-service
  jpa:
    properties:
      hibernate:
        sqldialect: org.hibernate.dialect.MySQLDialect
        showsql: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 